name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3
        sqlite3 --version  # Verify installed version

    - name: Upgrade SQLite
      run: |
        # Download and install SQLite 3.37.2
        wget https://www.sqlite.org/2022/sqlite-autoconf-3370200.tar.gz
        tar xzf sqlite-autoconf-3370200.tar.gz
        cd sqlite-autoconf-3370200
        ./configure
        make
        sudo make install
        sqlite3 --version  # Verify installed version

    - name: Run tests
      run: |
        pytest
