name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # or your desired Python version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake swig

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install faiss-cpu==1.7.4 --no-build-isolation --prefer-binary
        pip install -r requirements.txt  # Adjust this if you have other dependencies

    - name: Run tests
      run: |
        # Add your test command here
        pytest
