name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Using Python 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake swig libopenblas-dev python3-dev python3-numpy

    - name: Install FAISS from source
      run: |
        git clone https://github.com/facebookresearch/faiss.git
        cd faiss
        cmake -B build -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=$(which python3) .
        make -C build -j $(nproc)
        cd build/faiss/python
        python setup.py install

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel  # Install setuptools and wheel
        pip install pytest  # Ensure pytest is installed
        pip install -r requirements.txt  # Adjust this if you have other dependencies

    - name: Run tests
      run: |
        pytest
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.9.19/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
