name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Using Python 3.10

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake swig libopenblas-dev python3-dev python3-numpy

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel  # Install setuptools and wheel
        pip install faiss-cpu==1.7.4  # Install faiss-cpu from PyPI
        pip install pytest  # Ensure pytest is installed
        pip install -r requirements.txt  # Adjust this if you have other dependencies

    - name: Run tests
      run: |
        pytest
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
