name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have all dependencies listed in requirements.txt

      - name: Run script
        run: |
          python main.py  # Replace with the correct script name
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}  # Use the repository secret
