name: Install Latest sqlite3

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget

      - name: Download and install latest sqlite3
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3410000.tar.gz
          tar xzf sqlite-autoconf-3410000.tar.gz
          cd sqlite-autoconf-3410000
          ./configure
          make
          sudo make install

      - name: Check sqlite3 version
        run: |
          sqlite3 --version
