name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          # Update package list
          sudo apt-get update
          
          # Remove any existing SQLite versions
          sudo apt-get remove -y sqlite3 libsqlite3-dev
          
          # Install dependencies required for SQLite build
          sudo apt-get install -y wget build-essential

          # Download and install the latest SQLite version
          wget https://www.sqlite.org/2024/sqlite-autoconf-3390200.tar.gz
          tar xzf sqlite-autoconf-3390200.tar.gz
          cd sqlite-autoconf-3390200
          ./configure
          make
          sudo make install
